# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts
# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
# default env
ENV NODE_ENV=production

ENTRYPOINT ["node", "dist/index.js"]
